### PR TITLE
rafs: git rid of several unimplemented()

### LINKED ISSUE #1160: Fail to use nydus-image check -v
Fail to use nydus-image check -v to get information on bootstrap
image
image: alpine:3.17.2
image build cmd: ./nydusify convert --source alpine:3.17.2 --target dockerhub.kubekey.local/dfns/alpine_nydus:3.17.2 --target-insecure --fs-version 5
nydusify build commit:  54723319d5d5a3d412d6e22475ee9c19e0f4824c
nydus-image build commit : 54723319d5d5a3d412d6e22475ee9c19e0f4824c
nydusd build commit: 54723319d5d5a3d412d6e22475ee9c19e0f4824c
config:
{
    "device": {
        "backend": {
            "type": "registry",
            "config": {
                "scheme": "https",
                "host": "dockerhub.kubekey.local",
                "skip_verify": true,
                "auth": ""
            }
        },
        "cache": {
            "type": "blobcache",
            "config": {
                "work_dir": "/var/lib/nydus/cache/"
            }
        }
    },
    "mode": "direct",
    "digest_validate": false,
    "iostats_files": true,
    "enable_xattr": true,
    "access_pattern": true,
    "latest_read_files": true,
    "amplify_io": 0,
    "fs_prefetch": {
        "enable": false,
        "threads_count": 4,
        "merging_size": 131072,
        "bandwidth_rate": 1048576,
        "prefetch_all": false
    }
}

### PR DESCRIPTION
**Pull request by jiangliu**
The nydus-image check for v5 uses some unimplemented methods of InodeWrapper, which causes panicking at runtime.

Fixes: https://github.com/dragonflyoss/image-service/issues/1160

### CODE REVIEW

File: rafs/src/metadata/inode.rs [hunk 1]
```diff
@@ -338,7 +338,7 @@ impl InodeWrapper {
         match self {
             InodeWrapper::V5(i) => i.i_mtime,
             InodeWrapper::V6(i) => i.i_mtime,
-            InodeWrapper::Ref(_i) => unimplemented!(),
+            InodeWrapper::Ref(i) => i.get_attr().mtime,
```
Comment (imeoer) [inline rafs/src/metadata/inode.rs:341]: Is it necessary to implement it in other methods like `fn gid(&self)`, `fn uid(&self)`?

**Review by imeoer — APPROVED** [review]
