### PR TITLE
rafs v6: bug fix for the incorrect dirents process

### LINKED ISSUE #428: Nydusd-fuse panic when running in v6 format
image

### PR DESCRIPTION
**Pull request by pigletDips**
The dir file's dirents may occupy multiple blocks, and only the last
block may not be fully used. Previously, the last dirent of each block
is treated as the last dirent of the last block, which causes the
nydusd-fusedev to panic when using rafs v6 format.

To fix this bug, we process the last dirent of the last block different
from the last dirent of the other blocks.

fix #428 

Signed-off-by: Qi Wang <wangqi@linux.alibaba.com>

### CODE REVIEW

File: rafs/src/metadata/direct_v6.rs [hunk 1]
```diff
@@ -463,16 +463,20 @@ impl OndiskInodeWrapper {
                 let s = (de.e_nameoff - head_de.e_nameoff) as u64
                     + (size_of::<RafsV6Dirent>() * max_entries) as u64;
 
-                let e = slice::from_raw_parts(
-                    block_mapping.add(de.e_nameoff as usize),
-                    (self.size() % EROFS_BLOCK_SIZE - s) as usize,
-                );
+                let len = if div_round_up(self.size(), EROFS_BLOCK_SIZE) as usize == block_index + 1
```
Comment (liubogithub) [inline rafs/src/metadata/direct_v6.rs:466]: A comment is appreciated.

**Review by liubogithub — APPROVED** [review]
Looks good.

Can you please add a test case for it?

File: rafs/src/metadata/direct_v6.rs (hunk 1 above)
Comment (pigletDips) [reply rafs/src/metadata/direct_v6.rs:466]: OK

**Comment by pigletDips** [comment]
> Looks good.
> 
> Can you please add a test case for it?

The test case may be a little hard to implement. This mod lacks tests, and the dir inode and its dirents are pretty hard to construct.

**Comment by hsiangkao** [comment]
> > Looks good.
> > Can you please add a test case for it?
> 
> The test case may be a little hard to implement. This mod lacks tests, and the dir inode and its dirents are pretty hard to construct.

since it's already broken(because fuse use cases are not what we're mainly addressing) let's resolve it as another PR.

**Review by hsiangkao — APPROVED** [review]
