### PR TITLE
nydus-image nydus-cached: builds on macos

### LINKED ISSUE #423: nydus-image does not compile on macos
See https://github.com/bergwolf/image-service/runs/6402632511?check_suite_focus=true
```
error[E0433]: failed to resolve: could not find `linux` in `os`
  --> src/bin/nydus-image/core/node.rs:13:14
   |
13 | use std::os::linux::fs::MetadataExt;
   |              ^^^^^ could not find `linux` in `os`

error[E0432]: unresolved import `nix::sys::stat::makedev`
  --> src/bin/nydus-image/builder/stargz.rs:17:5
   |
17 | use nix::sys::stat::makedev;
   |     ^^^^^^^^^^^^^^^^^^^^^^^ no `makedev` in `sys::stat`

error[E0405]: cannot find trait `MetadataExt` in this scope
   --> src/bin/nydus-image/core/node.rs:851:[35](https://github.com/bergwolf/image-service/runs/6402632511?check_suite_focus=true#step:4:35)
    |
851 |     fn meta(&self) -> Result<impl MetadataExt> {
    |                                   ^^^^^^^^^^^ not found in this scope
    |
help: consider importing one of these items
    |
8   | use crate::builder::diff::thread::thread::env::os_imp::MetadataExt;
    |
8   | use crate::builder::diff::thread::thread::env::sys::platform::fs::MetadataExt;
    |
8   | use std::os::macos::fs::MetadataExt;
    |
8   | use std::os::unix::prelude::MetadataExt;
    |

error[E0425]: cannot find function `major` in module `stat`
   --> src/bin/nydus-image/core/node.rs:986:41
    |
986 |         self.inode.is_chrdev() && stat::major(self.rdev) == 0 && stat::minor(self.rdev) == 0
    |                                         ^^^^^ not found in `stat`

error[E0425]: cannot find function `minor` in module `stat`
   --> src/bin/nydus-image/core/node.rs:986:72
    |
986 |         self.inode.is_chrdev() && stat::major(self.rdev) == 0 && stat::minor(self.rdev) == 0
    |                                                                        ^^^^^ not found in `stat`

error[E0[40](https://github.com/bergwolf/image-service/runs/6402632511?check_suite_focus=true#step:4:40)5]: cannot find trait `MetadataExt` in this scope
    --> src/bin/nydus-image/core/node.rs:1518:26
     |
1518 |     fn set_inode_info<T: MetadataExt>(
     |                          ^^^^^^^^^^^ not found in this scope
     |
help: consider importing one of these items
     |
8    | use crate::builder::diff::thread::thread::env::os_imp::MetadataExt;
     |
8    | use crate::builder::diff::thread::thread::env::sys::platform::fs::MetadataExt;
     |
8    | use std::os::macos::fs::MetadataExt;
     |
8    | use std::os::unix::prelude::MetadataExt;
     |

error: aborting due to 6 previous errors
```

### PR DESCRIPTION
**Pull request by wanderxjtu**
fix #423

### CODE REVIEW

**Comment by yqleng1987** [comment]
@wanderxjtu , a new test job has been submitted. Please wait in patience.

**Comment by yqleng1987** [comment]
@wanderxjtu , The CI test is completed, please check result:
<table>
    <tr>
        <th colspan="2">Test Case</th><th>Test Result</th>
    </tr>
    <tr>
        <td colspan="2">merge-target-branch</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/5493>:white_check_mark:SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">build-docker-image</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/5493>:white_check_mark:SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">compile-nydus</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/5493>:x:FAIL</a></td>
    </tr>
</table>

Sorry, your test job failed. Please get the details in the link.

**Comment by yqleng1987** [comment]
@wanderxjtu , your pull request has been updated. A new test job will be submitted. Please wait in patience.

**Comment by yqleng1987** [comment]
@wanderxjtu , the test job has been submitted. Please wait in patience.

File: src/bin/nydus-image/core/bootstrap.rs [hunk 1]
```diff
@@ -264,10 +264,13 @@ impl Bootstrap {
         }
 
         // dot & dotdot
-        node.dirents
-            .push((node.offset, OsString::from("."), libc::S_IFDIR));
-        node.dirents
-            .push((parent_offset, OsString::from(".."), libc::S_IFDIR));
+        #[allow(clippy::useless_conversion)]
```
Comment (imeoer) [inline src/bin/nydus-image/core/bootstrap.rs:267]: Maybe we can explain why we do this.

Comment (wanderxjtu) [reply src/bin/nydus-image/core/bootstrap.rs:267]: Type of libc::S_IFDIR is u16 on macos, so it need a conversion; but compiler will report useless conversion on linux platform, so we add an allow annotation here.

File: Makefile [hunk 2]
```diff
@@ -92,8 +92,7 @@ ut:
 	RUST_BACKTRACE=1 ${CARGO} test $(VIRIOFS_COMMON) --bin nydusd -- --nocapture --test-threads=8
 
 macos-fusedev:
-	# nydus-cached/nydus-image does not support macos yet
-	${CARGO} build --target ${ARCH}-apple-darwin --target-dir ${current_dir}/target-fusedev --features=fusedev --release --bin nydusctl --bin nydusd
+	${CARGO} build --target ${ARCH}-apple-darwin --target-dir ${current_dir}/target-fusedev --features=fusedev --release --bin nydusctl --bin nydusd --bin nydus-image --bin nydus-cached
```
Comment (imeoer) [inline Makefile:95]: How about removing `--bin ... --bin ...`, so that we can build binaries that might be created in the future.

File: src/bin/nydus-image/core/bootstrap.rs (hunk 1 above)
Comment (imeoer) [reply src/bin/nydus-image/core/bootstrap.rs:267]: Thanks!

File: Makefile (hunk 2 above)
Comment (wanderxjtu) [reply Makefile:95]: blobfs still needs a lot of fixes to build on macos, so those `--bin` args cannot be removed for now.

**Comment by imeoer** [comment]
Thanks for the contribution!

Last suggestion, maybe we need to `mv` all binaries in the release pipeline here:
https://github.com/dragonflyoss/image-service/blob/master/.github/workflows/release.yml#L80

File: src/bin/nydus-image/core/node.rs [hunk 3]
```diff
@@ -999,7 +1001,15 @@ impl Node {
...
 
-        self.inode.is_chrdev() && stat::major(self.rdev) == 0 && stat::minor(self.rdev) == 0
+        #[cfg(target_os = "linux")]
+        {
+            use nix::sys::stat;
+            self.inode.is_chrdev() && stat::major(self.rdev) == 0 && stat::minor(self.rdev) == 0
+        }
+        #[cfg(target_os = "macos")]
+        {
+            self.inode.is_chrdev() && ((self.rdev >> 24) & 0xff) == 0 && (self.rdev & 0xffffff) == 0
```
Comment (bergwolf) [inline src/bin/nydus-image/core/node.rs:1011]: please add two more helpers `major_dev` and `minor_dev` to wrap around the differences between macos and linux.

File: src/lib.rs [hunk 4]
```diff
@@ -62,3 +63,14 @@ pub struct FsBackendDesc {
     pub mounted_time: DateTime<Local>,
     pub config: Option<serde_json::Value>,
 }
+
+pub fn makedev(major: u64, minor: u64) -> dev_t {
```
Comment (bergwolf) [inline src/lib.rs:67]: Please move it to `utils/src/compact.rs` where we can maintain these cross-target helpers.

File: src/bin/nydus-image/core/bootstrap.rs (hunk 1 above)
Comment (bergwolf) [reply src/bin/nydus-image/core/bootstrap.rs:267]: > Type of libc::S_IFDIR is u16 on macos, so it need a conversion; but compiler will report useless conversion on linux platform, so we add an allow annotation here.

Please add it to the code comment, thanks!

**Comment by yqleng1987** [comment]
@wanderxjtu , your pull request has been updated, but a test job is already running. A new test job wil be submitted after the current job is finished.

**Comment by yqleng1987** [comment]
@wanderxjtu , your test job is running now. Please wait in patience.

**Comment by yqleng1987** [comment]
@wanderxjtu , The CI test is completed, please check result:
<table>
    <tr>
        <th colspan="2">Test Case</th><th>Test Result</th>
    </tr>
    <tr>
        <td colspan="2">merge-target-branch</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/5516>:white_check_mark:SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">build-docker-image</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/5516>:white_check_mark:SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">compile-nydus</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/5516>:white_check_mark:SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">compile-ctr-remote</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/5516>:white_check_mark:SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">compile-nydus-snapshotter</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/5516>:white_check_mark:SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">start-nydus-snapshotter-config-containerd</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/5516>:white_check_mark:SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">run-container-with-nydus-image</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/5516>:white_check_mark:SUCCESS</a></td>
    </tr>
</table>

Sorry, the current test job result is not valid, because your pull request has been updated, and a new test job will be submitted.

**Comment by yqleng1987** [comment]
@wanderxjtu , your pull request has been updated. A new test job will be submitted. Please wait in patience.

**Comment by yqleng1987** [comment]
@wanderxjtu , the test job has been submitted. Please wait in patience.

**Comment by yqleng1987** [comment]
@wanderxjtu , The CI test is completed, please check result:
<table>
    <tr>
        <th colspan="2">Test Case</th><th>Test Result</th>
    </tr>
    <tr>
        <td colspan="2">merge-target-branch</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/5587>:white_check_mark:SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">build-docker-image</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/5587>:white_check_mark:SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">compile-nydus</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/5587>:white_check_mark:SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">compile-ctr-remote</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/5587>:white_check_mark:SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">compile-nydus-snapshotter</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/5587>:white_check_mark:SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">start-nydus-snapshotter-config-containerd</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/5587>:white_check_mark:SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">run-container-with-nydus-image</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/5587>:white_check_mark:SUCCESS</a></td>
    </tr>
</table>

Congratulations, your test job passed!

**Review by imeoer — APPROVED** [review]

**Review by jiangliu — APPROVED** [review]
