### PR TITLE
fix: amplify io is too large to hold in fuse buffer

### LINKED ISSUE #1270: nydus-image(v2.2.x) work error with some image in v5
Error image from https://quay.io/repository/jetstack/cert-manager-webhook?tab=tags tag: v1.7.1. When I use the alpine:latest from dockerhub,it all work fine. Is there some problems with the error image? However I try the fs-version 6 or nydus-image v2.1.x, it works fine.
```
 nydusify convert --source quay.io/jetstack/cert-manager-webhook:v1.7.1 --target dockerhub.kubekey.local/dfns/cert-manager-webhook:v1.7.1-nydus --fs-version 5 --target-insecure
```
Error:
```
INFO[2023-05-11T10:01:41+08:00] pulling image quay.io/jetstack/cert-manager-webhook:v1.7.1  module=converter
INFO[2023-05-11T10:01:47+08:00] pulled image quay.io/jetstack/cert-manager-webhook:v1.7.1, elapse 6.33375359s  module=converter
INFO[2023-05-11T10:01:47+08:00] converting image quay.io/jetstack/cert-manager-webhook:v1.7.1  module=converter
INFO[2023-05-11T10:01:48+08:00] [2023-05-11 10:01:48.549463 +08:00] ERROR [/src/error.rs:22] Error:  module=builder
INFO[2023-05-11T10:01:48+08:00]         "invalid parent inode"                       module=builder
INFO[2023-05-11T10:01:48+08:00]         at rafs/src/metadata/direct_v5.rs:446        module=builder
INFO[2023-05-11T10:01:48+08:00]         note: enable `RUST_BACKTRACE=1` env to display a backtrace  module=builder
INFO[2023-05-11T10:01:48+08:00] Error: Invalid argument (os error 22)         module=builder
ERRO[2023-05-11T10:01:48+08:00] fail to run nydus-image [merge --log-level warn --prefetch-policy fs --output-json tmp/nydus-converter-1688938698/merge-output.json --bootstrap tmp/nydus-converter-1688938698/bootstrap tmp/nydus-converter-1688938698/29e650d077251fe1bc57bac8aea1e4c9d40290582b85e24de9c826bbaece2629 tmp/nydus-converter-1688938698/69f06698ed1f5ca80d7a54df753f28d23159911f8cd60819b126c7fa36b97613 tmp/nydus-converter-1688938698/0303ee167a9dbfa6b990e930f5a5ceacfba2bc1bb072eb261daa50ca81d24edd]  error="exit status 1"
FATA[2023-05-11T10:01:48+08:00] convert image: merge nydus layers: copy bootstrap targz into content store: merge nydus bootstrap: merge bootstrap: run merge command: exit status 1
```
Debug INFO:
```
INFO[2023-05-11T10:02:34+08:00] pulling image quay.io/jetstack/cert-manager-webhook:v1.7.1  module=converter
DEBU[2023-05-11T10:02:34+08:00] resolving                                     host=quay.io
DEBU[2023-05-11T10:02:34+08:00] do request                                    host=quay.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=containerd/1.7.0+unknown request.method=HEAD url="https://quay.io/v2/jetstack/cert-manager-webhook/manifests/v1.7.1"
DEBU[2023-05-11T10:02:36+08:00] fetch response received                       host=quay.io response.header.content-length=1723 response.header.content-type=application/vnd.docker.distribution.manifest.list.v2+json response.header.date="Thu, 11 May 2023 02:02:37 GMT" response.header.docker-content-digest="sha256:a926d60b6f23553ca5d11ac9cd66bcc692136e838613c8bc0d60c6c35a3cbcfc" response.header.server=nginx/1.20.1 response.header.strict-transport-security="max-age=63072000; preload" response.header.x-frame-options=DENY response.status="200 OK" url="https://quay.io/v2/jetstack/cert-manager-webhook/manifests/v1.7.1"
DEBU[2023-05-11T10:02:36+08:00] resolved                                      desc.digest="sha256:a926d60b6f23553ca5d11ac9cd66bcc692136e838613c8bc0d60c6c35a3cbcfc" host=quay.io
DEBU[2023-05-11T10:02:36+08:00] fetch                                         digest="sha256:a926d60b6f23553ca5d11ac9cd66bcc692136e838613c8bc0d60c6c35a3cbcfc" mediatype=application/vnd.docker.distribution.manifest.list.v2+json size=1723
DEBU[2023-05-11T10:02:36+08:00] do request                                    digest="sha256:a926d60b6f23553ca5d11ac9cd66bcc692136e838613c8bc0d60c6c35a3cbcfc" mediatype=application/vnd.docker.distribution.manifest.list.v2+json request.header.accept="application/vnd.docker.distribution.manifest.list.v2+json, */*" request.header.user-agent=containerd/1.7.0+unknown request.method=GET size=1723 url="https://quay.io/v2/jetstack/cert-manager-webhook/manifests/sha256:a926d60b6f23553ca5d11ac9cd66bcc692136e838613c8bc0d60c6c35a3cbcfc"
DEBU[2023-05-11T10:02:37+08:00] fetch response received                       digest="sha256:a926d60b6f23553ca5d11ac9cd66bcc692136e838613c8bc0d60c6c35a3cbcfc" mediatype=application/vnd.docker.distribution.manifest.list.v2+json response.header.content-length=1723 response.header.content-type=application/vnd.docker.distribution.manifest.list.v2+json response.header.date="Thu, 11 May 2023 02:02:38 GMT" response.header.docker-content-digest="sha256:a926d60b6f23553ca5d11ac9cd66bcc692136e838613c8bc0d60c6c35a3cbcfc" response.header.server=nginx/1.20.1 response.header.strict-transport-security="max-age=63072000; preload" response.header.x-frame-options=DENY response.status="200 OK" size=1723 url="https://quay.io/v2/jetstack/cert-manager-webhook/manifests/sha256:a926d60b6f23553ca5d11ac9cd66bcc692136e838613c8bc0d60c6c35a3cbcfc"
DEBU[2023-05-11T10:02:37+08:00] fetch                                         digest="sha256:2baefe47a12e936448f7a6a6ed60708ab86855a1ff2b3318da993501de45d6bf" mediatype=application/vnd.docker.distribution.manifest.v2+json size=947
DEBU[2023-05-11T10:02:37+08:00] do request                                    digest="sha256:2baefe47a12e936448f7a6a6ed60708ab86855a1ff2b3318da993501de45d6bf" mediatype=application/vnd.docker.distribution.manifest.v2+json request.header.accept="application/vnd.docker.distribution.manifest.v2+json, */*" request.header.user-agent=containerd/1.7.0+unknown request.method=GET size=947 url="https://quay.io/v2/jetstack/cert-manager-webhook/manifests/sha256:2baefe47a12e936448f7a6a6ed60708ab86855a1ff2b3318da993501de45d6bf"
DEBU[2023-05-11T10:02:38+08:00] fetch response received                       digest="sha256:2baefe47a12e936448f7a6a6ed60708ab86855a1ff2b3318da993501de45d6bf" mediatype=application/vnd.docker.distribution.manifest.v2+json response.header.content-length=947 response.header.content-type=application/vnd.docker.distribution.manifest.v2+json response.header.date="Thu, 11 May 2023 02:02:39 GMT" response.header.docker-content-digest="sha256:2baefe47a12e936448f7a6a6ed60708ab86855a1ff2b3318da993501de45d6bf" response.header.server=nginx/1.20.1 response.header.strict-transport-security="max-age=63072000; preload" response.header.x-frame-options=DENY response.status="200 OK" size=947 url="https://quay.io/v2/jetstack/cert-manager-webhook/manifests/sha256:2baefe47a12e936448f7a6a6ed60708ab86855a1ff2b3318da993501de45d6bf"
DEBU[2023-05-11T10:02:38+08:00] fetch                                         digest="sha256:efd4cd7e0f1ae7643a1325cf951a7da9b950e1cc02256dd951459584beb60ac7" mediatype=application/vnd.docker.image.rootfs.diff.tar.gzip size=65596
DEBU[2023-05-11T10:02:38+08:00] fetch                                         digest="sha256:2df365faf0e3007f983fadd7a65ba51d41b488eb2ed8fc70f4bf97043cfea560" mediatype=application/vnd.docker.image.rootfs.diff.tar.gzip size=803833
DEBU[2023-05-11T10:02:38+08:00] fetch                                         digest="sha256:b9b4b2124eafe7232c5c9fcfddd3650e7f687a02f5889f51f1ad4fc0898ac714" mediatype=application/vnd.docker.image.rootfs.diff.tar.gzip size=12763928
DEBU[2023-05-11T10:02:38+08:00] fetch                                         digest="sha256:36736adc2f4b56924e5e3a46cc8f8eaf9b18c3c6aac310b01c200a3f4a6f400c" mediatype=application/vnd.docker.container.image.v1+json size=886
DEBU[2023-05-11T10:02:38+08:00] do request                                    digest="sha256:efd4cd7e0f1ae7643a1325cf951a7da9b950e1cc02256dd951459584beb60ac7" mediatype=application/vnd.docker.image.rootfs.diff.tar.gzip request.header.accept="application/vnd.docker.image.rootfs.diff.tar.gzip, */*" request.header.user-agent=containerd/1.7.0+unknown request.method=GET size=65596 url="https://quay.io/v2/jetstack/cert-manager-webhook/blobs/sha256:efd4cd7e0f1ae7643a1325cf951a7da9b950e1cc02256dd951459584beb60ac7"
DEBU[2023-05-11T10:02:38+08:00] do request                                    digest="sha256:2df365faf0e3007f983fadd7a65ba51d41b488eb2ed8fc70f4bf97043cfea560" mediatype=application/vnd.docker.image.rootfs.diff.tar.gzip request.header.accept="application/vnd.docker.image.rootfs.diff.tar.gzip, */*" request.header.user-agent=containerd/1.7.0+unknown request.method=GET size=803833 url="https://quay.io/v2/jetstack/cert-manager-webhook/blobs/sha256:2df365faf0e3007f983fadd7a65ba51d41b488eb2ed8fc70f4bf97043cfea560"
DEBU[2023-05-11T10:02:38+08:00] do request                                    digest="sha256:36736adc2f4b56924e5e3a46cc8f8eaf9b18c3c6aac310b01c200a3f4a6f400c" mediatype=application/vnd.docker.container.image.v1+json request.header.accept="application/vnd.docker.container.image.v1+json, */*" request.header.user-agent=containerd/1.7.0+unknown request.method=GET size=886 url="https://quay.io/v2/jetstack/cert-manager-webhook/blobs/sha256:36736adc2f4b56924e5e3a46cc8f8eaf9b18c3c6aac310b01c200a3f4a6f400c"
DEBU[2023-05-11T10:02:38+08:00] do request                                    digest="sha256:b9b4b2124eafe7232c5c9fcfddd3650e7f687a02f5889f51f1ad4fc0898ac714" mediatype=application/vnd.docker.image.rootfs.diff.tar.gzip request.header.accept="application/vnd.docker.image.rootfs.diff.tar.gzip, */*" request.header.user-agent=containerd/1.7.0+unknown request.method=GET size=12763928 url="https://quay.io/v2/jetstack/cert-manager-webhook/blobs/sha256:b9b4b2124eafe7232c5c9fcfddd3650e7f687a02f5889f51f1ad4fc0898ac714"
DEBU[2023-05-11T10:02:39+08:00] fetch response received                       digest="sha256:36736adc2f4b56924e5e3a46cc8f8eaf9b18c3c6aac310b01c200a3f4a6f400c" mediatype=application/vnd.docker.container.image.v1+json response.header.accept-ranges=bytes response.header.age=81653 response.header.content-length=886 response.header.content-type=binary/octet-stream response.header.date="Wed, 10 May 2023 03:21:48 GMT" response.header.etag="\"9fd2a7e99448c34ad24eada20f7aa4a8-1\"" response.header.last-modified="Fri, 04 Feb 2022 15:59:27 GMT" response.header.server=AmazonS3 response.header.via="1.1 c9006eba4649f733be848dcf116b7e3a.cloudfront.net (CloudFront)" response.header.x-amz-cf-id="DJCmFMfUziNtIBkXuEEVqVhhhRb1CKmwmweQ-CNOjSkK6C11rnaPsg==" response.header.x-amz-cf-pop=HKG54-C1 response.header.x-amz-replication-status=COMPLETED response.header.x-amz-server-side-encryption=AES256 response.header.x-amz-version-id=Ti2ZJO5QOodwxNf.6ICXq5HbREavkGPO response.header.x-cache="Hit from cloudfront" response.status="200 OK" size=886 url="https://quay.io/v2/jetstack/cert-manager-webhook/blobs/sha256:36736adc2f4b56924e5e3a46cc8f8eaf9b18c3c6aac310b01c200a3f4a6f400c"
DEBU[2023-05-11T10:02:39+08:00] fetch response received                       digest="sha256:efd4cd7e0f1ae7643a1325cf951a7da9b950e1cc02256dd951459584beb60ac7" mediatype=application/vnd.docker.image.rootfs.diff.tar.gzip response.header.accept-ranges=bytes response.header.age=263538 response.header.content-length=65596 response.header.content-type=binary/octet-stream response.header.date="Mon, 08 May 2023 00:50:22 GMT" response.header.etag="\"97319c17ebf9afb2bd1dccead044104a-1\"" response.header.last-modified="Tue, 21 Dec 2021 17:24:55 GMT" response.header.server=AmazonS3 response.header.via="1.1 abe726b1571439a6268136ea3851d872.cloudfront.net (CloudFront)" response.header.x-amz-cf-id="FkOzr29Xf3ZR1pO0Ewg616fD-zioYpwp1rQ8OHfLwHpx-flVwBDTIQ==" response.header.x-amz-cf-pop=HKG54-C1 response.header.x-amz-replication-status=COMPLETED response.header.x-amz-server-side-encryption=AES256 response.header.x-amz-version-id=RgBlC.GtGl1ZamUK9kyPPnJYwCgng6pS response.header.x-cache="Hit from cloudfront" response.status="200 OK" size=65596 url="https://quay.io/v2/jetstack/cert-manager-webhook/blobs/sha256:efd4cd7e0f1ae7643a1325cf951a7da9b950e1cc02256dd951459584beb60ac7"
DEBU[2023-05-11T10:02:39+08:00] fetch response received                       digest="sha256:2df365faf0e3007f983fadd7a65ba51d41b488eb2ed8fc70f4bf97043cfea560" mediatype=application/vnd.docker.image.rootfs.diff.tar.gzip response.header.accept-ranges=bytes response.header.age=605797 response.header.content-length=803833 response.header.content-type=binary/octet-stream response.header.date="Thu, 04 May 2023 01:46:03 GMT" response.header.etag="\"657cf464438353b920146fc5ec9a194b-1\"" response.header.last-modified="Sat, 25 Dec 2021 11:06:04 GMT" response.header.server=AmazonS3 response.header.via="1.1 52c5ddb029eae46cd9dad0cfd50b5b8e.cloudfront.net (CloudFront)" response.header.x-amz-cf-id="kmmedgOYztj9WNlh_uKszHumnL0nLq1FErmV8NliFDjZTnLx4-M3Jg==" response.header.x-amz-cf-pop=HKG54-C1 response.header.x-amz-replication-status=COMPLETED response.header.x-amz-server-side-encryption=AES256 response.header.x-amz-storage-class=INTELLIGENT_TIERING response.header.x-amz-version-id=xr1P61zALd6UOvwF6pwe3rkQ5DjTYc7h response.header.x-cache="Hit from cloudfront" response.status="200 OK" size=803833 url="https://quay.io/v2/jetstack/cert-manager-webhook/blobs/sha256:2df365faf0e3007f983fadd7a65ba51d41b488eb2ed8fc70f4bf97043cfea560"
DEBU[2023-05-11T10:02:39+08:00] fetch response received                       digest="sha256:b9b4b2124eafe7232c5c9fcfddd3650e7f687a02f5889f51f1ad4fc0898ac714" mediatype=application/vnd.docker.image.rootfs.diff.tar.gzip response.header.accept-ranges=bytes response.header.age=81651 response.header.content-length=12763928 response.header.content-type=binary/octet-stream response.header.date="Wed, 10 May 2023 03:21:50 GMT" response.header.etag="\"2e4a39986605cc72dfce04b914308c0b-1\"" response.header.last-modified="Fri, 04 Feb 2022 15:59:24 GMT" response.header.server=AmazonS3 response.header.via="1.1 7d1ba0397af493cf13f301d061e292ac.cloudfront.net (CloudFront)" response.header.x-amz-cf-id="tUsN7Zs1Tu5apEctskC_uoG_-twBYQi5NZiko0jhoyOvZeN3vErFzQ==" response.header.x-amz-cf-pop=HKG54-C1 response.header.x-amz-replication-status=COMPLETED response.header.x-amz-server-side-encryption=AES256 response.header.x-amz-storage-class=INTELLIGENT_TIERING response.header.x-amz-version-id=fB_cC5yJtnNoc7cO4LlIqcAMJ3SpzoP1 response.header.x-cache="Hit from cloudfront" response.status="200 OK" size=12763928 url="https://quay.io/v2/jetstack/cert-manager-webhook/blobs/sha256:b9b4b2124eafe7232c5c9fcfddd3650e7f687a02f5889f51f1ad4fc0898ac714"
INFO[2023-05-11T10:02:41+08:00] pulled image quay.io/jetstack/cert-manager-webhook:v1.7.1, elapse 6.583657528s  module=converter
INFO[2023-05-11T10:02:41+08:00] converting image quay.io/jetstack/cert-manager-webhook:v1.7.1  module=converter
DEBU[2023-05-11T10:02:41+08:00] using pigz for decompression
DEBU[2023-05-11T10:02:41+08:00]         Command: nydus-image create --log-level warn --prefetch-policy fs --blob tmp/nydus-converter-156170348/blob.rafs --whiteout-spec none --fs-version 5 --type tar-rafs --blob-inline-meta --compressor zstd --chunk-size 0x100000 tmp/nydus-converter-156170348/blob.targz
DEBU[2023-05-11T10:02:41+08:00]         Command: nydus-image create --log-level warn --prefetch-policy fs --blob tmp/nydus-converter-2099487682/blob.rafs --whiteout-spec none --fs-version 5 --type tar-rafs --blob-inline-meta --compressor zstd --chunk-size 0x100000 tmp/nydus-converter-2099487682/blob.targz
DEBU[2023-05-11T10:02:41+08:00]         Command: nydus-image create --log-level warn --prefetch-policy fs --blob tmp/nydus-converter-3938049330/blob.rafs --whiteout-spec none --fs-version 5 --type tar-rafs --blob-inline-meta --compressor zstd --chunk-size 0x100000 tmp/nydus-converter-3938049330/blob.targz
DEBU[2023-05-11T10:02:41+08:00] converted                                     new="&{application/vnd.oci.image.layer.nydus.blob.v1 sha256:0303ee167a9dbfa6b990e930f5a5ceacfba2bc1bb072eb261daa50ca81d24edd 51244 [] map[] [] <nil> }" old="{application/vnd.docker.image.rootfs.diff.tar.gzip sha256:efd4cd7e0f1ae7643a1325cf951a7da9b950e1cc02256dd951459584beb60ac7 65596 [] map[] [] <nil> }"
DEBU[2023-05-11T10:02:41+08:00] converted                                     new="&{application/vnd.oci.image.layer.nydus.blob.v1 sha256:29e650d077251fe1bc57bac8aea1e4c9d40290582b85e24de9c826bbaece2629 1365696 [] map[] [] <nil> }" old="{application/vnd.docker.image.rootfs.diff.tar.gzip sha256:2df365faf0e3007f983fadd7a65ba51d41b488eb2ed8fc70f4bf97043cfea560 803833 [] map[] [] <nil> }"
DEBU[2023-05-11T10:02:42+08:00] converted                                     new="&{application/vnd.oci.image.layer.nydus.blob.v1 sha256:69f06698ed1f5ca80d7a54df753f28d23159911f8cd60819b126c7fa36b97613 11605952 [] map[] [] <nil> }" old="{application/vnd.docker.image.rootfs.diff.tar.gzip sha256:b9b4b2124eafe7232c5c9fcfddd3650e7f687a02f5889f51f1ad4fc0898ac714 12763928 [] map[] [] <nil> }"
DEBU[2023-05-11T10:02:42+08:00] converted                                     new="&{application/vnd.docker.container.image.v1+json sha256:16cebd7da38b5ecd3e4889575665d719ba03a5177d1c4083f4c2bd4f43b0ce98 886 [] map[] [] <nil> }" old="{application/vnd.docker.container.image.v1+json sha256:36736adc2f4b56924e5e3a46cc8f8eaf9b18c3c6aac310b01c200a3f4a6f400c 886 [] map[] [] <nil> }"
DEBU[2023-05-11T10:02:42+08:00]         Command: nydus-image merge --log-level warn --prefetch-policy fs --output-json tmp/nydus-converter-2536036893/merge-output.json --bootstrap tmp/nydus-converter-2536036893/bootstrap tmp/nydus-converter-2536036893/29e650d077251fe1bc57bac8aea1e4c9d40290582b85e24de9c826bbaece2629 tmp/nydus-converter-2536036893/69f06698ed1f5ca80d7a54df753f28d23159911f8cd60819b126c7fa36b97613 tmp/nydus-converter-2536036893/0303ee167a9dbfa6b990e930f5a5ceacfba2bc1bb072eb261daa50ca81d24edd
INFO[2023-05-11T10:02:42+08:00] [2023-05-11 10:02:42.625920 +08:00] ERROR [/src/error.rs:22] Error:  module=builder
INFO[2023-05-11T10:02:42+08:00]         "invalid parent inode"                       module=builder
INFO[2023-05-11T10:02:42+08:00]         at rafs/src/metadata/direct_v5.rs:446        module=builder
INFO[2023-05-11T10:02:42+08:00]         note: enable `RUST_BACKTRACE=1` env to display a backtrace  module=builder
INFO[2023-05-11T10:02:42+08:00] Error: Invalid argument (os error 22)         module=builder
ERRO[2023-05-11T10:02:42+08:00] fail to run nydus-image [merge --log-level warn --prefetch-policy fs --output-json tmp/nydus-converter-2536036893/merge-output.json --bootstrap tmp/nydus-converter-2536036893/bootstrap tmp/nydus-converter-2536036893/29e650d077251fe1bc57bac8aea1e4c9d40290582b85e24de9c826bbaece2629 tmp/nydus-converter-2536036893/69f06698ed1f5ca80d7a54df753f28d23159911f8cd60819b126c7fa36b97613 tmp/nydus-converter-2536036893/0303ee167a9dbfa6b990e930f5a5ceacfba2bc1bb072eb261daa50ca81d24edd]  error="exit status 1"
FATA[2023-05-11T10:02:42+08:00] convert image: merge nydus layers: copy bootstrap targz into content store: merge nydus bootstrap: merge bootstrap: run merge command: exit status 1
```

The errors happend in nydus-image v2.2.x. When I use the v2.1.6, work fine. 
```
root@nydus:/usr/local/bin# nydus-image --version
Version:        v2.2.0
Git Commit:     a38f6b8d6257af90d59880265335dd55fab07668
Build Time:     2023-03-01T10:05:57.267573846Z
Profile:        release
Rustc:          rustc 1.66.1 (90743e729 2023-01-10)
```

```
root@nydus:/usr/local/bin# nydus-image --version
Version:        v2.2.1
Git Commit:     04fb92c5aa980deedf62e69cc2294195a88bab31
Build Time:     2023-05-04T07:28:49.522159639Z
Profile:        release
Rustc:          rustc 1.66.1 (90743e729 2023-01-10)
```
```
Nydusify version
Version : v2.2.0-134-g902fd718.m
Revision        : 902fd7181984e7fc31f6640b142162a787047ac9.m
Go version      : go1.19.3
Build time      : 2023-04-08T10:25:14
```

### LINKED ISSUE #1312: Add test case of amplify_io larger than fuse buffer size
Fuse buffer size is 1052656

### PR DESCRIPTION
**Pull request by ccx1024cc**
Fuse request buffer is fixed by `FUSE_KERN_BUF_SIZE * pagesize() + FUSE_HEADER_ SIZE`. When amplify io is larger than it, FuseDevWriter suffers from smaller buffer. As a result, invalid data error is returned.

##  Reproduction
    run nydusd with 3MB amplify_io
    error from random io:
        reply error header OutHeader { len: 16, error: -5, unique: 108 }, error Custom { kind: InvalidData, error: "data out of range, available 1052656 requested 1250066" }

## Details
    size of fuse buffer = 1052656 + 16 (size of inner header) = 256(FUSE_KERN_BUF_SIZE) * 4096(page size) + 4096(fuse header)
    let amplify_io = min(user_specified, fuseWriter.available_bytes())

## Resolution
   Evalucation of amplify_io will be replaced with [ZeroCopyWriter.available_bytes()]("https://github.com/cloud-hypervisor/fuse-backend-rs/pull/135").

## Relevant Issue
#1270
ci: https://github.com/dragonflyoss/image-service/actions/runs/4931748472/jobs/8814099799
#1312

### CODE REVIEW

**Comment by jiangliu** [comment]
How about adding `available_bytes()` to `ZeroCopyWriter`?

**Comment by bergwolf** [comment]
> How about adding available_bytes() to ZeroCopyWriter?

It has just been merged. https://github.com/cloud-hypervisor/fuse-backend-rs/pull/135

**Comment by bergwolf** [comment]
Please add test case (https://github.com/dragonflyoss/image-service/issues/1312) in the same PR (in a different commit) so that the change is verified at the same time.

File: service/src/fusedev.rs [hunk 1]
```diff
@@ -121,6 +122,7 @@ impl FuseServer {
                     format!("failed to get fuse request from /dev/fuse, {}", e),
                 )
             })? {
+                FUSE_BUF_SIZE.store(writer.available_bytes() as u32, Ordering::Relaxed);
```
Comment (bergwolf) [inline service/src/fusedev.rs:125]: Let's avoid `FUSE_BUF_SIZE ` bouncing buffer by adding a comparison first:
```rust
if FUSE_BUF_SIZE.load(Ordering::Relaxed) != writer.available_bytes() {
    FUSE_BUF_SIZE.store(writer.available_bytes() as u32, Ordering::Relaxed);
}
```

**Comment by adamqqqplay** [comment]
Thanks for your great work!

**Comment by jiangliu** [comment]
Could you please help to rebase onto the latest fuse-backend-rs version?

File: smoke/tests/native_layer_test.go [hunk 2]
```diff
@@ -77,6 +78,67 @@ func (n *NativeLayerTestSuite) TestMakeLayers() test.Generator {
...
+		Dimension(paramRafsMode, []interface{}{"direct"}).
+		Dimension(paramEnablePrefetch, []interface{}{true}).
+		Dimension(paramBatch, []interface{}{"0x100000"}).
+		Dimension(paramEncrypt, []interface{}{false}).
+
+		/* amplify io - target param */
+		Dimension(paramAmplifyIO, []interface{}{uint64(0x0), uint64(0x100000), uint64(0x10000000)}).
+		Skip(func(param *tool.DescartesItem) bool {
+
+			// rafs v6 not support cached mode nor dummy cache
```
Comment (imeoer) [inline smoke/tests/native_layer_test.go:109]: Please follow the go comment style, starting with a capital letter.

File: rafs/src/fs.rs [hunk 3]
```diff
@@ -621,19 +621,20 @@ impl FileSystem for Rafs {
         assert!(!descs.is_empty() && !descs[0].is_empty());
 
         // Try to amplify user io for Rafs v5, to improve performance.
-        if self.sb.meta.is_v5() && size < self.amplify_io {
+        let amplify_io = cmp::min(self.amplify_io as usize, w.available_bytes()) as u32;
```
Comment (imeoer) [inline rafs/src/fs.rs:624]: Does this user-specified `amplify_io` can't exceed `FUSE_KERN_BUF_SIZE * pagesize() + FUSE_HEADER_ SIZE` (about 1MB?) ?

Comment (ccx1024cc) [reply rafs/src/fs.rs:624]: > Does this user-specified `amplify_io` can't exceed `FUSE_KERN_BUF_SIZE * pagesize() + FUSE_HEADER_ SIZE` (about 1MB?) ?

Yes, the actual read size must be smaller than 1052656.

**Review by bergwolf — APPROVED** [review]
lgtm

File: rafs/src/fs.rs (hunk 3 above)
Comment (imeoer) [reply rafs/src/fs.rs:624]: Maybe give a warning to the user?

Comment (ccx1024cc) [reply rafs/src/fs.rs:624]: > Maybe give a warning to the user?

Ok, there will be another pr, which adjust tips for user
