### PR TITLE
[registry] Disable token refresh thread when prefetch is enabled

### LINKED ISSUE #1777: [Bug] refresh token thread fails to renew token after expiration
### Problem Description

For images pulled from either ACR or GCR, I'm seeing a lot of `failed to refresh registry token` errors in my nydusd logs every 10 minutes (the default refresh interval). I'm using the CRI method of getting credentials for the nydus-snapshotter. The credentials are initially generated by the acr-credential-provider and gcr-credential-provider kubelet helpers and the credentials generated this way are inherently ephemeral so it's expected that they aren't valid anymore after a few hours.
For this exact reason, I run with `prefetch` enabled as I know my creds are bound to expire at one point. But I'm a bit surprised that the `refresh_token_thread` keeps going in the background even after the prefetch is completely done.

Is there any reason for the thread to try refreshing credentials over and over? Or should it stop at one point? Like when prefetch is completed for instance or maybe after a certain amount of consecutive failures?

I've noticed that the function has a [break condition](https://github.com/dragonflyoss/nydus/blob/master/storage/src/backend/registry.rs#L958) but I'm not sure what's supposed to trigger it?

### Expected Behavior

We shouldn't see error messages related to token refresh if we have finished pulling everything we need from the registry

### Actual Behavior

After starting a pod from an image in GCR, the following logs appear after 12 hours:
```
Oct 03 04:24:17 containerd-nydus-grpc[2532]: [2025-10-03 04:24:17.665228 +00:00] DEBUG [/reqwest-0.11.27/src/connect.rs:449] starting new connection: https://europe-docker.pkg.dev/
Oct 03 04:24:17 containerd-nydus-grpc[2532]: [2025-10-03 04:24:17.733858 +00:00] DEBUG [/src/backend/connection.rs:716]  Request: GET https://europe-docker.pkg.dev/v2/token headers: Some({}), proxy: false, data: false, duration: 68ms
Oct 03 04:24:17 containerd-nydus-grpc[2532]: [2025-10-03 04:24:17.734058 +00:00] WARN [/src/backend/registry.rs:383] failed to request registry auth server by GET method: ErrorWithMsg("{\"errors\":[{\"code\":\"UNAUTHORIZED\",\"message\":\"authentication failed\"}]}\n")
Oct 03 04:24:17 containerd-nydus-grpc[2532]: [2025-10-03 04:24:17.734104 +00:00] ERROR [/src/backend/registry.rs:985] [refresh_token_thread] failed to refresh registry token
Oct 03 04:24:22 containerd-nydus-grpc[3065]: [2025-10-03 04:24:22.170340 +00:00] DEBUG [/reqwest-0.11.27/src/connect.rs:449] starting new connection: https://europe-docker.pkg.dev/
Oct 03 04:24:22 containerd-nydus-grpc[3065]: [2025-10-03 04:24:22.238751 +00:00] DEBUG [/src/backend/connection.rs:716]  Request: GET https://europe-docker.pkg.dev/v2/token headers: Some({}), proxy: false, data: false, duration: 68ms
Oct 03 04:24:22 containerd-nydus-grpc[3065]: [2025-10-03 04:24:22.238950 +00:00] WARN [/src/backend/registry.rs:383] failed to request registry auth server by GET method: ErrorWithMsg("{\"errors\":[{\"code\":\"UNAUTHORIZED\",\"message\":\"authentication failed\"}]}\n")
Oct 03 04:24:22 containerd-nydus-grpc[3065]: [2025-10-03 04:24:22.238978 +00:00] ERROR [/src/backend/registry.rs:985] [refresh_token_thread] failed to refresh registry token
```

And similarly for ACR (except that it starts after 3 hours)

### How to reproduce

Have an image in a private GCR or ACR registry and start a container with it. Nydusd should start pumping out error messages after a few hours.

### Environment Details

- Nydus-snapshotter version: v0.15.0
- Nydus version: v2.3.2
- Container runtime: Containerd v2.1.1
- Operating System: Linux
- Kernel version: 6.8

### Additional Information

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Fricounet**
## Overview
_Please briefly describe the changes your pull request makes._

Add a new RegistryConfig field called `enable_token_refresh` that will decide whether the registry refresh token thread is started on not. 

## Related Issues
_Please link to the relevant issue. For example: `Fix #123` or `Related #456`._

Fix #1777

## Change Details
_Please describe your changes in detail:_

The new field will be set to true by default but will be disabled when prefetch is enabled. The refresh thread is disabled in this case because it becomes useless once everything has been prefetched and it's unlikely that tokens would expire during the time it takes for the prefetch to run (as it would mean that regular image pulls  would be likely to fail as well because they download the layers in a similar time to the prefetch)

## Test Results
_If you have any relevant screenshots or videos that can help illustrate your changes, please add them here._

Running tests with this basic nydusd config:
```
{
  "device": {
    "backend": {
      "type": "registry",
      "config": {
        "timeout": 15,
        "connect_timeout": 15,
        "retry_limit": 5
      }
    },
    "cache": {
      "type": "blobcache",
      "config": {
        "work_dir": "cache"
      }
    }
  },
  "mode": "direct",
  "digest_validate": false,
  "iostats_files": false,
  "enable_xattr": true,
  "fs_prefetch": {
    "enable": true,
    "threads_count": 4
  }
}
```

The token thread isn't started:
```
INFO[2025-10-13T11:38:56.430857078+02:00] nydusd command: /containerd-local/nydusd fuse --config /containerd-local/io.containerd.snapshotter.v1.nydus/config/d3mchc1jjoq9cr38fp00/config.json --bootstrap /containerd-local/io.containerd.snapshotter.v1.nydus/snapshots/24/fs/image.boot --mountpoint /containerd-local/io.containerd.snapshotter.v1.nydus/snapshots/24/mnt --apisock /containerd-local/io.containerd.snapshotter.v1.nydus/socket/d3mchc1jjoq9cr38fp00/api.sock --log-level debug --log-rotation-size 100
[2025-10-13 11:38:56.437379 +02:00] INFO Program Version: v2.3.7-dd, Git Commit: "c100686d6b0243c451f1a261b900497f827c90aa", Build Time: "2025-10-13T09:38:39.942636660Z", Profile: "debug", Rustc Version: "rustc 1.84.0 (9fc6b4312 2025-01-07)"
[2025-10-13 11:38:56.437525 +02:00] INFO Set rlimit-nofile to 1000000, maximum 1000000
[2025-10-13 11:38:56.438354 +02:00] DEBUG [/fuse-backend-rs-0.12.1/src/api/pseudo_fs.rs:161] pseudo fs iterate "/"
[2025-10-13 11:38:56.439288 +02:00] INFO RAFS features: HASH_BLAKE3 | EXPLICIT_UID_GID | HAS_XATTR | COMPRESSION_ZSTD | INLINED_CHUNK_DIGEST | ENCRYPTION_NONE
[2025-10-13 11:38:56.439831 +02:00] INFO backend config: ConnectionConfig { proxy: ProxyConfig { url: "", ping_url: "", fallback: false, check_interval: 5, use_http: false, check_pause_elapsed: 300 }, skip_verify: false, timeout: 15, connect_timeout: 15, retry_limit: 5 }
[2025-10-13 11:38:56.454946 +02:00] INFO Refresh token thread is disabled.
```

## Change Type
_Please select the type of change your pull request relates to:_
- [x] Bug Fix
- [ ] Feature Addition
- [ ] Documentation Update
- [ ] Code Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe)

## Self-Checklist
_Before submitting a pull request, please ensure you have completed the following:_
- [ ] I have run a code style check and addressed any warnings/errors.
- [ ] I have added appropriate comments to my code (if applicable).
- [ ] I have updated the documentation (if applicable).
- [ ] I have written appropriate unit tests.

### CODE REVIEW

File: api/src/config.rs [hunk 1]
```diff
@@ -1509,10 +1524,19 @@ impl TryFrom<&BlobCacheEntryConfig> for BlobCacheEntryConfigV2 {
...
             prefetch_config: v.prefetch_config.clone(),
         };
+        let mut backend: BackendConfigV2 = (&backend_config).try_into()?;
+
+        // If prefetch is enabled, disable token refresh by default
+        if cache_config.prefetch_config.enable {
+            if let Some(registry) = backend.registry.as_mut() {
+                registry.enable_token_refresh = false;
+            }
+        }
```
Comment (Fricounet) [inline api/src/config.rs:1529]: not quite sure if the change in the BlobCacheEntryConfig is needed too

File: api/src/config.rs [hunk 2]
```diff
@@ -626,6 +626,10 @@ pub struct RegistryConfig {
     /// Enable HTTP proxy for the read request.
     #[serde(default)]
     pub proxy: ProxyConfig,
+    /// Enable background token refresh thread. Defaults to true.
+    /// When prefetch is enabled, this can be disabled as prefetch traffic will naturally refresh tokens.
+    #[serde(default = "default_enable_token_refresh")]
+    pub enable_token_refresh: bool,
```
Comment (imeoer) [inline api/src/config.rs]: Thanks for the PR! How about defining the option like:

```
#[serde(skip_deserializing)]
pub disable_token_refresh: bool,
```

I think we can remove the refresh token logic directly and implement singleinflight mechanism for get token in the future.

Comment (Fricounet) [reply api/src/config.rs]: Sure! I've pushed a new commit with the opposite semantic.

> I think we can remove the refresh token logic directly and implement singleinflight mechanism for get token in the future.

Agreed, it would simplify things
